# Generated by Django 2.1.7 on 2019-02-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sea_map', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('map_size', models.IntegerField(default=0)),
                ('rows', models.CharField(max_length=45)),
                ('cols', models.CharField(max_length=45, verbose_name='columns')),
                ('initial_data', models.CharField(max_length=60)),
            ],
        ),
    ]
